### PR TITLE
Code formated

### PR DESCRIPTION
**Pull request by Dharna5599**
Hey @paul-shannon,
I have formated the code using the [styler](https://github.com/r-lib/styler).
Please have a look.

### CODE REVIEW

**Review by paul-shannon — COMMENTED** [review]
@Dharna5599 - looks promising!  Does the package still build fine, demos run?

**Comment by Dharna5599** [comment]
Hey @paul-shannon,
I tried building the package and It's working totally fine after the reinstallation.
Screenshot from 2021-02-07 11-53-17

**Comment by paul-shannon** [comment]
Thank you, @Dharna5599!

**Comment by Dharna5599** [comment]
Thankyou @paul-shannon for merging the PR.
I am a GSoC aspirant and wanted to contribute more to the project, to have a good exposure before the proposal submission period starts.
I will be very glad if you can help me finding few more issues, on which I can work on.

**Comment by paul-shannon** [comment]
@Dharna5599 - grateful for your enthusiasm!  

See https://github.com/cytoscape/cyjShiny/issues/29

**Comment by paul-shannon** [comment]
@Dharna5599   layout overview for cytoscape.js  can be found here:
https://blog.js.cytoscape.org/2020/05/11/layouts/

**Comment by Dharna5599** [comment]
Thankyou @paul-shannon .
I will go through the links which you have sent and will update soon.

**Pull request merged**
