### PR TITLE
layouts-added

### PR DESCRIPTION
**Pull request by Dharna5599**
Hey @paul-shannon ,
I was going through #29 and got to know about how the package works.
I found that few layout features were missing so I added four of them and tested it locally.

Coming to #29, I think I will need some more info inorder to resolve it.

### CODE REVIEW

**Comment by Dharna5599** [comment]
Hey @paul-shannon,
Is it okay if I give you my GSOC proposal for final approval (review) before sending it to the main portal or should I submit it directly?

**Comment by paul-shannon** [comment]
I’ll be glad to take a look.   

 - Paul

**Comment by Dharna5599** [comment]
Hey @paul-shannon 
Is there some way I can get your email address where I can give you the proposal?

**Comment by paul-shannon** [comment]
***@***.***

**Comment by Dharna5599** [comment]
Hey @paul-shannon,
Please accept my apologies if this bothers you, but I am unable to understand the email address you have provided, could you please send me back the response?

**Comment by paul-shannon** [comment]
Ah, github does not allow emails - or so it seems.

Best idea I have on the spur of the moment is for you to find this page, which provides a mail-to link:

   https://isbscience.org/bio/paul-shannon/

**Comment by Dharna5599** [comment]
Thank you

**Comment by paul-shannon** [comment]
There may be some delay in routing mail from the web page I sent you.

So how about this?   I just pushed cyjShiny/doc/notes.txt with my email addresses.
 
 - Paul

**Comment by Dharna5599** [comment]
Hey @paul-shannon,
This will undoubtedly work, and I have received your email address.
Thank you
Dharna

**Comment by Dharna5599** [comment]
Hey @paul-shannon,
I successfully sent you my proposal to one of the given email addresses.  Is it safe to assume, it reached you because there were two email addresses given and I only sent it to one of them?

**Comment by paul-shannon** [comment]
I have it - thanks.  Sorry for the delay.  I’ve been busy, and recovering from my second covid vaccine.  I’ll try to get you a response later this week.

**Comment by Dharna5599** [comment]
Hey @paul-shannon,
Thank you for responding and I hope that each new day takes you closer to a complete and speedy recovery!
May good health envelop you.

**Comment by paul-shannon** [comment]
post-merge comment, if I may:  @Dharna5599.
As it stands, I  do not know how ```bundle.js``` was created, or which layouts were added.
Here is what would be very helpful - forgive me if you have already added this and I missed it:

- good clear notes about what you added, and why
- script/s and a makefile to reproduce (and/or extend) your work

Thank you!

**Comment by Dharna5599** [comment]
Hi @paul-shannon, 
 As you suggested, I'm working on documentation to make a clear note of how I added some layouts that were previously missing in cyjShiny, and after the consultation, I'll send it here via github.

**Pull request merged**
